#!/bin/sh
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Helsinki 2>&1 | col -bx > Helsinki-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Glasgow 2>&1 | col -bx > Glasgow-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p London 2>&1 | col -bx > London-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Lexington 2>&1 | col -bx > Lexington-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Kamata 2>&1 | col -bx > Kamata-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Rosario 2>&1 | col -bx > Rosario-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Recife 2>&1 | col -bx > Recife-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Montreal 2>&1 | col -bx > Montreal-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p AbuDhabi 2>&1 | col -bx > AbuDhabi-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Kiev 2>&1 | col -bx > Kiev-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Gladstone 2>&1 | col -bx > Gladstone-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Chicago 2>&1 | col -bx > Chicago-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Alexandria 2>&1 | col -bx > Alexandria-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Lisbon 2>&1 | col -bx > Lisbon-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Berlin 2>&1 | col -bx > Berlin-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Dublin 2>&1 | col -bx > Dublin-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Vancouver 2>&1 | col -bx > Vancouver-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Marseille 2>&1 | col -bx > Marseille-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Brussels 2>&1 | col -bx > Brussels-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Montpellier 2>&1 | col -bx > Montpellier-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Tokyo 2>&1 | col -bx > Tokyo-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Firenze 2>&1 | col -bx > Firenze-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Bilbao 2>&1 | col -bx > Bilbao-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Wolfsburg 2>&1 | col -bx > Wolfsburg-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Chiangmai 2>&1 | col -bx > Chiangmai-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Amsterdam 2>&1 | col -bx > Amsterdam-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Salzburg 2>&1 | col -bx > Salzburg-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Phoenix 2>&1 | col -bx > Phoenix-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Darwin 2>&1 | col -bx > Darwin-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Zurich 2>&1 | col -bx > Zurich-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Miami 2>&1 | col -bx > Miami-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Milpitas 2>&1 | col -bx > Milpitas-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Kingston 2>&1 | col -bx > Kingston-mrswatson.txt
mrswatson --display-info --plugin-root /Library/Audio/Plug-Ins/VST/KORG -p Madrid 2>&1 | col -bx > Madrid-mrswatson.txt
