{
  "ni8": [
    [{
      "autoname": false,
      "id": 0,
      "name": "Level",
      "section": "Master",
      "vflag": false
    }, {
      "autoname": false,
      "id": 1,
      "name": "Tune",
      "vflag": false
    }, {
      "autoname": false,
      "id": 18,
      "name": "<%=name[1]%>",
      "section": "Param",
      "vflag": false
    }, {
      "autoname": false,
      "id": 19,
      "name": "<%=name[2]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 20,
      "name": "<%=name[3]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 21,
      "name": "<%=name[4]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 22,
      "name": "<%=name[5]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 23,
      "name": "<%=name[6]%>",
      "vflag": false
    }],
    [{
      "autoname": false,
      "id": 24,
      "name": "<%=name[7]%>",
      "section": "Param",
      "vflag": false
    }, {
      "autoname": false,
      "id": 25,
      "name": "<%=name[8]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 26,
      "name": "<%=name[9]%>",
      "section": "FX",
      "vflag": false
    }, {
      "autoname": false,
      "id": 27,
      "name": "<%=name[10]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 28,
      "name": "<%=name[11]%>",
      "section": "Env",
      "vflag": false
    }, {
      "autoname": false,
      "id": 29,
      "name": "<%=name[12]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 30,
      "name": "<%=name[13]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 31,
      "name": "<%=name[14]%>",
      "vflag": false
    }],
    [{
      "autoname": false,
      "id": 32,
      "name": "<%=name[15]%>",
      "section": "Env",
      "vflag": false
    }, {
      "autoname": false,
      "id": 33,
      "name": "<%=name[16]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 34,
      "name": "<%=name[17]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 35,
      "name": "<%=name[18]%>",
      "vflag": false
    }, {
      "autoname": false,
      "id": 36,
      "name": "<%=name[19]%>",
      "vflag": false
    }, {
      "autoname": true,
      "vflag": false
    }, {
      "autoname": true,
      "vflag": false
    }, {
      "autoname": true,
      "vflag": false
    }]
  ]
}
