module.exports = [
  {id:   0, name: 'MasterVol'       section=''}
  {id:   1, name: 'A Vol'           section=''}
  {id:   2, name: 'A Pan'           section=''}
  {id:   3, name: 'A Octave'        section=''}
  {id:   4, name: 'A Semi'          section=''}
  {id:   5, name: 'A Fine'          section=''}
  {id:   6, name: 'A Unison'        section=''}
  {id:   7, name: 'A UniDet'        section=''}
  {id:   8, name: 'A UniBlend'      section=''}
  {id:   9, name: 'A Warp'          section=''}
  {id:  10, name: 'A CoarsePit'     section=''}
  {id:  11, name: 'A WTPos'         section=''}
  {id:  12, name: 'A RandPhase'     section=''}
  {id:  13, name: 'A Phase'         section=''}
  {id:  14, name: 'B Vol'           section=''}
  {id:  15, name: 'B Pan'           section=''}
  {id:  16, name: 'B Octave'        section=''}
  {id:  17, name: 'B Semi'          section=''}
  {id:  18, name: 'B Fine'          section=''}
  {id:  19, name: 'B Unison'        section=''}
  {id:  20, name: 'B UniDet'        section=''}
  {id:  21, name: 'B UniBlend'      section=''}
  {id:  22, name: 'B Warp'          section=''}
  {id:  23, name: 'B CoarsePit'     section=''}
  {id:  24, name: 'B WTPos'         section=''}
  {id:  25, name: 'B RandPhase'     section=''}
  {id:  26, name: 'B Phase'         section=''}
  {id:  27, name: 'Noise Level'     section=''}
  {id:  28, name: 'Noise Pitch'     section=''}
  {id:  29, name: 'Noise Fine'      section=''}
  {id:  30, name: 'Noise Pan'       section=''}
  {id:  31, name: 'Noise RandPhase' section=''}
  {id:  32, name: 'Noise Phase'     section=''}
  {id:  33, name: 'Sub Osc Level'   section=''}
  {id:  34, name: 'Sub Osc Pan'     section=''}
  {id:  35, name: 'Env1 Atk'        section=''}
  {id:  36, name: 'Env1 Hold'       section=''}
  {id:  37, name: 'Env1 Dec'        section=''}
  {id:  38, name: 'Env1 Sus'        section=''}
  {id:  39, name: 'Env1 Rel'        section=''}
  {id:  40, name: 'OscA>Fil'        section=''}
  {id:  41, name: 'OscB>Fil'        section=''}
  {id:  42, name: 'OscN>Fil'        section=''}
  {id:  43, name: 'OscS>Fil'        section=''}
  {id:  44, name: 'Fil Type'        section=''}
  {id:  45, name: 'Fil Cutoff'      section=''}
  {id:  46, name: 'Fil Reso'        section=''}
  {id:  47, name: 'Fil Driv'        section=''}
  {id:  48, name: 'Fil Var'         section=''}
  {id:  49, name: 'Fil Mix'         section=''}
  {id:  50, name: 'Fil Stereo'      section=''}
  {id:  51, name: 'Env2 Atk'        section=''}
  {id:  52, name: 'Env2 Hld'        section=''}
  {id:  53, name: 'Env2 Dec'        section=''}
  {id:  54, name: 'Env2 Sus'        section=''}
  {id:  55, name: 'Env2 Rel'        section=''}
  {id:  56, name: 'Env3 Atk'        section=''}
  {id:  57, name: 'Env3 Hld'        section=''}
  {id:  58, name: 'Env3 Dec'        section=''}
  {id:  59, name: 'Env3 Sus'        section=''}
  {id:  60, name: 'Env3 Rel'        section=''}
  {id:  61, name: 'LFO1 Rate'       section=''}
  {id:  62, name: 'LFO2 Rate'       section=''}
  {id:  63, name: 'LFO3 Rate'       section=''}
  {id:  64, name: 'LFO4 Rate'       section=''}
  {id:  65, name: 'PortTime'        section=''}
  {id:  66, name: 'PortCurve'       section=''}
  {id:  67, name: 'Chaos1 BPM'      section=''}
  {id:  68, name: 'Chaos2 BPM'      section=''}
  {id:  69, name: 'Chaos1 Rate'     section=''}
  {id:  70, name: 'Chaos2 Rate'     section=''}
  {id:  71, name: 'A curve1'        section=''}
  {id:  72, name: 'D curve1'        section=''}
  {id:  73, name: 'R curve1'        section=''}
  {id:  74, name: 'A curve2'        section=''}
  {id:  75, name: 'D curve2'        section=''}
  {id:  76, name: 'R curve2'        section=''}
  {id:  77, name: 'A curve3'        section=''}
  {id:  78, name: 'D curve3'        section=''}
  {id:  79, name: 'R curve3'        section=''}
  {id:  80, name: 'Mast.Tun'        section=''}
  {id:  81, name: 'Verb Wet'        section=''}
  {id:  82, name: 'VerbSize'        section=''}
  {id:  83, name: 'Decay'           section=''}
  {id:  84, name: 'VerbLoCt'        section=''}
  {id:  85, name: 'Spin Rate'       section=''}
  {id:  86, name: 'VerbHiCt'        section=''}
  {id:  87, name: 'Spin Depth'      section=''}
  {id:  88, name: 'EQ FrqL'         section=''}
  {id:  89, name: 'EQ FrqH'         section=''}
  {id:  90, name: 'EQ Q L'          section=''}
  {id:  91, name: 'EQ Q H'          section=''}
  {id:  92, name: 'EQ VolL'         section=''}
  {id:  93, name: 'EQ VolH'         section=''}
  {id:  94, name: 'EQ TypL'         section=''}
  {id:  95, name: 'EQ TypH'         section=''}
  {id:  96, name: 'Dist_Wet'        section=''}
  {id:  97, name: 'Dist_Drv'        section=''}
  {id:  98, name: 'Dist_L/B/H'      section=''}
  {id:  99, name: 'Dist_Mode'       section=''}
  {id: 100, name: 'Dist_Freq'       section=''}
  {id: 101, name: 'Dist_BW'         section=''}
  {id: 102, name: 'Dist_PrePost'    section=''}
  {id: 103, name: 'Flg_Wet'         section=''}
  {id: 104, name: 'Flg_BPM_Sync'    section=''}
  {id: 105, name: 'Flg_Rate'        section=''}
  {id: 106, name: 'Flg_Dep'         section=''}
  {id: 107, name: 'Flg_Feed'        section=''}
  {id: 108, name: 'Flg_Stereo'      section=''}
  {id: 109, name: 'Phs_Wet'         section=''}
  {id: 110, name: 'Phs_BPM_Sync'    section=''}
  {id: 111, name: 'Phs_Rate'        section=''}
  {id: 112, name: 'Phs_Dpth'        section=''}
  {id: 113, name: 'Phs_Frq'         section=''}
  {id: 114, name: 'Phs_Feed'        section=''}
  {id: 115, name: 'Phs_Stereo'      section=''}
  {id: 116, name: 'Cho_Wet'         section=''}
  {id: 117, name: 'Cho_BPM_Sync'    section=''}
  {id: 118, name: 'Cho_Rate'        section=''}
  {id: 119, name: 'Cho_Dly'         section=''}
  {id: 120, name: 'Cho_Dly2'        section=''}
  {id: 121, name: 'Cho_Dep'         section=''}
  {id: 122, name: 'Cho_Feed'        section=''}
  {id: 123, name: 'Cho_Filt'        section=''}
  {id: 124, name: 'Dly_Wet'         section=''}
  {id: 125, name: 'Dly_Freq'        section=''}
  {id: 126, name: 'Dly_BW'          section=''}
  {id: 127, name: 'Dly_BPM_Sync'    section=''}
  {id: 128, name: 'Dly_Link'        section=''}
  {id: 129, name: 'Dly_TimL'        section=''}
  {id: 130, name: 'Dly_TimR'        section=''}
  {id: 131, name: 'Dly_Mode'        section=''}
  {id: 132, name: 'Dly_Feed'        section=''}
  {id: 133, name: 'Dly_Off L'       section=''}
  {id: 134, name: 'Dly_Off R'       section=''}
  {id: 135, name: 'Cmp_Thr'         section=''}
  {id: 136, name: 'Cmp_Rat'         section=''}
  {id: 137, name: 'Cmp_Att'         section=''}
  {id: 138, name: 'Cmp_Rel'         section=''}
  {id: 139, name: 'CmpGain'         section=''}
  {id: 140, name: 'CmpMBnd'         section=''}
  {id: 141, name: 'FX Fil Wet'      section=''}
  {id: 142, name: 'FX Fil Type'     section=''}
  {id: 143, name: 'FX Fil Freq'     section=''}
  {id: 144, name: 'FX Fil Reso'     section=''}
  {id: 145, name: 'FX Fil Drive'    section=''}
  {id: 146, name: 'FX Fil Var'      section=''}
  {id: 147, name: 'Hyp_Wet'         section=''}
  {id: 148, name: 'Hyp_Rate'        section=''}
  {id: 149, name: 'Hyp_Detune'      section=''}
  {id: 150, name: 'Hyp_Unison'      section=''}
  {id: 151, name: 'Hyp_Retrig'      section=''}
  {id: 152, name: 'HypDim_Size'     section=''}
  {id: 153, name: 'HypDim_Mix'      section=''}
  {id: 154, name: 'Dist Enable'     section=''}
  {id: 155, name: 'Flg Enable'      section=''}
  {id: 156, name: 'Phs Enable'      section=''}
  {id: 157, name: 'Cho Enable'      section=''}
  {id: 158, name: 'Dly Enable'      section=''}
  {id: 159, name: 'Comp Enable'     section=''}
  {id: 160, name: 'Rev Enable'      section=''}
  {id: 161, name: 'EQ Enable'       section=''}
  {id: 162, name: 'FX Fil Enable'   section=''}
  {id: 163, name: 'Hyp Enable'      section=''}
  {id: 164, name: 'OscAPitchTrack'  section=''}
  {id: 165, name: 'OscBPitchTrack'  section=''}
  {id: 166, name: 'Bend U'          section=''}
  {id: 167, name: 'Bend D'          section=''}
  {id: 168, name: 'WarpOscA'        section=''}
  {id: 169, name: 'WarpOscB'        section=''}
  {id: 170, name: 'SubOscShape'     section=''}
  {id: 171, name: 'SubOscOctave'    section=''}
  {id: 172, name: 'A Uni LR'        section=''}
  {id: 173, name: 'B Uni LR'        section=''}
  {id: 174, name: 'A Uni Warp'      section=''}
  {id: 175, name: 'B Uni Warp'      section=''}
  {id: 176, name: 'A Uni WTPos'     section=''}
  {id: 177, name: 'B Uni WTPos'     section=''}
  {id: 178, name: 'A Uni Stack'     section=''}
  {id: 179, name: 'B Uni Stack'     section=''}
  {id: 180, name: 'Mod 1 amt'       section=''}
  {id: 181, name: 'Mod 1 out'       section=''}
  {id: 182, name: 'Mod 2 amt'       section=''}
  {id: 183, name: 'Mod 2 out'       section=''}
  {id: 184, name: 'Mod 3 amt'       section=''}
  {id: 185, name: 'Mod 3 out'       section=''}
  {id: 186, name: 'Mod 4 amt'       section=''}
  {id: 187, name: 'Mod 4 out'       section=''}
  {id: 188, name: 'Mod 5 amt'       section=''}
  {id: 189, name: 'Mod 5 out'       section=''}
  {id: 190, name: 'Mod 6 amt'       section=''}
  {id: 191, name: 'Mod 6 out'       section=''}
  {id: 192, name: 'Mod 7 amt'       section=''}
  {id: 193, name: 'Mod 8 out'       section=''}
  {id: 194, name: 'Mod 8 amt'       section=''}
  {id: 195, name: 'Mod 8 out'       section=''}
  {id: 196, name: 'Mod 9 amt'       section=''}
  {id: 197, name: 'Mod 9 out'       section=''}
  {id: 198, name: 'Mod10 amt'       section=''}
  {id: 199, name: 'Mod10 out'       section=''}
  {id: 200, name: 'Mod11 amt'       section=''}
  {id: 201, name: 'Mod11 out'       section=''}
  {id: 202, name: 'Mod12 amt'       section=''}
  {id: 203, name: 'Mod12 out'       section=''}
  {id: 204, name: 'Mod13 amt'       section=''}
  {id: 205, name: 'Mod13 out'       section=''}
  {id: 206, name: 'Mod14 amt'       section=''}
  {id: 207, name: 'Mod14 out'       section=''}
  {id: 208, name: 'Mod15 amt'       section=''}
  {id: 209, name: 'Mod15 out'       section=''}
  {id: 210, name: 'Mod16 amt'       section=''}
  {id: 211, name: 'Mod16 out'       section=''}
  {id: 212, name: 'Osc A On'        section=''}
  {id: 213, name: 'Osc B On'        section=''}
  {id: 214, name: 'Osc N On'        section=''}
  {id: 215, name: 'Osc S On'        section=''}
  {id: 216, name: 'Filter On'       section=''}
  {id: 217, name: 'Mod Wheel'       section=''}
  {id: 218, name: 'Macro 1'         section=''}
  {id: 219, name: 'Macro 2'         section=''}
  {id: 220, name: 'Macro 3'         section=''}
  {id: 221, name: 'Macro 4'         section=''}
  {id: 222, name: 'Amp.'            section=''}
  {id: 223, name: 'LFO1 smooth'     section=''}
  {id: 224, name: 'LFO2 smooth'     section=''}
  {id: 225, name: 'LFO3 smooth'     section=''}
  {id: 226, name: 'LFO4 smooth'     section=''}
  {id: 227, name: 'Pitch Bend'      section=''}
  {id: 228, name: 'Mod17 amt'       section=''}
  {id: 229, name: 'Mod17 out'       section=''}
  {id: 230, name: 'Mod18 amt'       section=''}
  {id: 231, name: 'Mod18 out'       section=''}
  {id: 232, name: 'Mod19 amt'       section=''}
  {id: 233, name: 'Mod19 out'       section=''}
  {id: 234, name: 'Mod20 amt'       section=''}
  {id: 235, name: 'Mod20 out'       section=''}
  {id: 236, name: 'Mod21 amt'       section=''}
  {id: 237, name: 'Mod21 out'       section=''}
  {id: 238, name: 'Mod22 amt'       section=''}
  {id: 239, name: 'Mod22 out'       section=''}
  {id: 240, name: 'Mod23 amt'       section=''}
  {id: 241, name: 'Mod23 out'       section=''}
  {id: 242, name: 'Mod24 amt'       section=''}
  {id: 243, name: 'Mod24 out'       section=''}
  {id: 244, name: 'Mod25 amt'       section=''}
  {id: 245, name: 'Mod25 out'       section=''}
  {id: 246, name: 'Mod26 amt'       section=''}
  {id: 247, name: 'Mod26 out'       section=''}
  {id: 248, name: 'Mod27 amt'       section=''}
  {id: 249, name: 'Mod27 out'       section=''}
  {id: 250, name: 'Mod28 amt'       section=''}
  {id: 251, name: 'Mod28 out'       section=''}
  {id: 252, name: 'Mod29 amt'       section=''}
  {id: 253, name: 'Mod29 out'       section=''}
  {id: 254, name: 'Mod30 amt'       section=''}
  {id: 255, name: 'Mod30 out'       section=''}
  {id: 256, name: 'Mod31 amt'       section=''}
  {id: 257, name: 'Mod31 out'       section=''}
  {id: 258, name: 'Mod32 amt'       section=''}
  {id: 259, name: 'Mod32 out'       section=''}
  {id: 260, name: 'LFO5 Rate'       section=''}
  {id: 261, name: 'LFO6 Rate'       section=''}
  {id: 262, name: 'LFO7 Rate'       section=''}
  {id: 263, name: 'LFO8 Rate'       section=''}
  {id: 264, name: 'LFO5 smooth'     section=''}
  {id: 265, name: 'LFO6 smooth'     section=''}
  {id: 266, name: 'LFO7 smooth'     section=''}
  {id: 267, name: 'LFO8 smooth'     section=''}
  {id: 268, name: 'FX Fil Pan'      section=''}
  {id: 269, name: 'Comp_Wet'        section=''}
  {id: 270, name: 'CompMB L'        section=''}
  {id: 271, name: 'CompMB M'        section=''}
  {id: 272, name: 'CompMB H'        section=''}
]