module.exports = [
  {id:  0, name: 'Global Bypass'           section=''}
  {id:  1, name: 'Global Dirty Flag'       section=''}
  {id:  2, name: 'Global Input Gain'       section=''}
  {id:  3, name: 'Global Output Gain'      section=''}
  {id:  4, name: 'C1 B1 Bypass'            section=''}
  {id:  5, name: 'C1 B1 Attack'            section=''}
  {id:  6, name: 'C1 B1 Ratio'             section=''}
  {id:  7, name: 'C1 B1 Release'           section=''}
  {id:  8, name: 'C1 B1 Knee'              section=''}
  {id:  9, name: 'C1 B1 Threshold'         section=''}
  {id: 10, name: 'C1 B1 Gain'              section=''}
  {id: 11, name: 'C1 B1 Mix'               section=''}
  {id: 12, name: 'C1 B2 Bypass'            section=''}
  {id: 13, name: 'C1 B2 Attack'            section=''}
  {id: 14, name: 'C1 B2 Ratio'             section=''}
  {id: 15, name: 'C1 B2 Release'           section=''}
  {id: 16, name: 'C1 B2 Knee'              section=''}
  {id: 17, name: 'C1 B2 Threshold'         section=''}
  {id: 18, name: 'C1 B2 Gain'              section=''}
  {id: 19, name: 'C1 B2 Mix'               section=''}
  {id: 20, name: 'C1 B3 Bypass'            section=''}
  {id: 21, name: 'C1 B3 Attack'            section=''}
  {id: 22, name: 'C1 B3 Ratio'             section=''}
  {id: 23, name: 'C1 B3 Release'           section=''}
  {id: 24, name: 'C1 B3 Knee'              section=''}
  {id: 25, name: 'C1 B3 Threshold'         section=''}
  {id: 26, name: 'C1 B3 Gain'              section=''}
  {id: 27, name: 'C1 B3 Mix'               section=''}
  {id: 28, name: 'C1 Level Detection Meth' section=''}
  {id: 29, name: 'C1 Auto Release'         section=''}
  {id: 30, name: 'C1 Auto Gain'            section=''}
  {id: 31, name: 'C1 Detection Filter HP ' section=''}
  {id: 32, name: 'C1 Detection Filter HP ' section=''}
  {id: 33, name: 'C1 Detection Filter LP ' section=''}
  {id: 34, name: 'C1 Detection Filter LP ' section=''}
  {id: 35, name: 'C1 Vintage Mode'         section=''}
  {id: 36, name: 'C1 Global Gain'          section=''}
  {id: 37, name: 'C1 Global Mix'           section=''}
  {id: 38, name: 'C1 Process LFE'          section=''}
]