module.exports = [
  {id:  0, name: 'Global Bypass'      section=''}
  {id:  1, name: 'Global Dirty Flag'  section=''}
  {id:  2, name: 'Global Input Gain'  section=''}
  {id:  3, name: 'Global Output Gain' section=''}
  {id:  4, name: 'TS B1 Attack'       section=''}
  {id:  5, name: 'TS B1 Bypass'       section=''}
  {id:  6, name: 'TS B1 Contour'      section=''}
  {id:  7, name: 'TS B1 Sustain'      section=''}
  {id:  8, name: 'TS B2 Attack'       section=''}
  {id:  9, name: 'TS B2 Bypass'       section=''}
  {id: 10, name: 'TS B2 Contour'      section=''}
  {id: 11, name: 'TS B2 Sustain'      section=''}
  {id: 12, name: 'TS B3 Attack'       section=''}
  {id: 13, name: 'TS B3 Bypass'       section=''}
  {id: 14, name: 'TS B3 Contour'      section=''}
  {id: 15, name: 'TS B3 Sustain'      section=''}
  {id: 16, name: 'TS Global Mode'     section=''}
  {id: 17, name: 'TS Global Mix'      section=''}
  {id: 18, name: 'TS Process LFE'     section=''}
]