module.exports = [
  {id:   0, name: 'Global Bypass'           section=''}
  {id:   1, name: 'Global Dirty Flag'       section=''}
  {id:   2, name: 'Global Input Gain'       section=''}
  {id:   3, name: 'Global Output Gain'      section=''}
  {id:   4, name: 'C1 Module Bypass'        section=''}
  {id:   5, name: 'C2 Module Bypass'        section=''}
  {id:   6, name: 'EQ Module Bypass'        section=''}
  {id:   7, name: 'EXC Module Bypass'       section=''}
  {id:   8, name: 'TS Module Bypass'        section=''}
  {id:   9, name: 'Neutrino Mode'           section=''}
  {id:  10, name: 'Neutrino Amount'         section=''}
  {id:  11, name: 'Neutrino Detail'         section=''}
  {id:  12, name: 'C1 B1 Bypass'            section=''}
  {id:  13, name: 'C1 B1 Attack'            section=''}
  {id:  14, name: 'C1 B1 Ratio'             section=''}
  {id:  15, name: 'C1 B1 Release'           section=''}
  {id:  16, name: 'C1 B1 Knee'              section=''}
  {id:  17, name: 'C1 B1 Threshold'         section=''}
  {id:  18, name: 'C1 B1 Gain'              section=''}
  {id:  19, name: 'C1 B1 Mix'               section=''}
  {id:  20, name: 'C1 B2 Bypass'            section=''}
  {id:  21, name: 'C1 B2 Attack'            section=''}
  {id:  22, name: 'C1 B2 Ratio'             section=''}
  {id:  23, name: 'C1 B2 Release'           section=''}
  {id:  24, name: 'C1 B2 Knee'              section=''}
  {id:  25, name: 'C1 B2 Threshold'         section=''}
  {id:  26, name: 'C1 B2 Gain'              section=''}
  {id:  27, name: 'C1 B2 Mix'               section=''}
  {id:  28, name: 'C1 B3 Bypass'            section=''}
  {id:  29, name: 'C1 B3 Attack'            section=''}
  {id:  30, name: 'C1 B3 Ratio'             section=''}
  {id:  31, name: 'C1 B3 Release'           section=''}
  {id:  32, name: 'C1 B3 Knee'              section=''}
  {id:  33, name: 'C1 B3 Threshold'         section=''}
  {id:  34, name: 'C1 B3 Gain'              section=''}
  {id:  35, name: 'C1 B3 Mix'               section=''}
  {id:  36, name: 'C1 Level Detection Meth' section=''}
  {id:  37, name: 'C1 Auto Release'         section=''}
  {id:  38, name: 'C1 Auto Gain'            section=''}
  {id:  39, name: 'C1 Detection Filter HP ' section=''}
  {id:  40, name: 'C1 Detection Filter HP ' section=''}
  {id:  41, name: 'C1 Detection Filter LP ' section=''}
  {id:  42, name: 'C1 Detection Filter LP ' section=''}
  {id:  43, name: 'C1 Vintage Mode'         section=''}
  {id:  44, name: 'C1 Global Gain'          section=''}
  {id:  45, name: 'C1 Global Mix'           section=''}
  {id:  46, name: 'C1 Process LFE'          section=''}
  {id:  47, name: 'C2 B1 Bypass'            section=''}
  {id:  48, name: 'C2 B1 Attack'            section=''}
  {id:  49, name: 'C2 B1 Ratio'             section=''}
  {id:  50, name: 'C2 B1 Release'           section=''}
  {id:  51, name: 'C2 B1 Knee'              section=''}
  {id:  52, name: 'C2 B1 Threshold'         section=''}
  {id:  53, name: 'C2 B1 Gain'              section=''}
  {id:  54, name: 'C2 B1 Mix'               section=''}
  {id:  55, name: 'C2 B2 Bypass'            section=''}
  {id:  56, name: 'C2 B2 Attack'            section=''}
  {id:  57, name: 'C2 B2 Ratio'             section=''}
  {id:  58, name: 'C2 B2 Release'           section=''}
  {id:  59, name: 'C2 B2 Knee'              section=''}
  {id:  60, name: 'C2 B2 Threshold'         section=''}
  {id:  61, name: 'C2 B2 Gain'              section=''}
  {id:  62, name: 'C2 B2 Mix'               section=''}
  {id:  63, name: 'C2 B3 Bypass'            section=''}
  {id:  64, name: 'C2 B3 Attack'            section=''}
  {id:  65, name: 'C2 B3 Ratio'             section=''}
  {id:  66, name: 'C2 B3 Release'           section=''}
  {id:  67, name: 'C2 B3 Knee'              section=''}
  {id:  68, name: 'C2 B3 Threshold'         section=''}
  {id:  69, name: 'C2 B3 Gain'              section=''}
  {id:  70, name: 'C2 B3 Mix'               section=''}
  {id:  71, name: 'C2 Level Detection Meth' section=''}
  {id:  72, name: 'C2 Auto Release'         section=''}
  {id:  73, name: 'C2 Auto Gain'            section=''}
  {id:  74, name: 'C2 Detection Filter HP ' section=''}
  {id:  75, name: 'C2 Detection Filter HP ' section=''}
  {id:  76, name: 'C2 Detection Filter LP ' section=''}
  {id:  77, name: 'C2 Detection Filter LP ' section=''}
  {id:  78, name: 'C2 Vintage Mode'         section=''}
  {id:  79, name: 'C2 Global Gain'          section=''}
  {id:  80, name: 'C2 Global Mix'           section=''}
  {id:  81, name: 'C2 Process LFE'          section=''}
  {id:  82, name: 'EQ HP Frequency'         section=''}
  {id:  83, name: 'EQ LS Frequency'         section=''}
  {id:  84, name: 'EQ B1 Frequency'         section=''}
  {id:  85, name: 'EQ B2 Frequency'         section=''}
  {id:  86, name: 'EQ B3 Frequency'         section=''}
  {id:  87, name: 'EQ B4 Frequency'         section=''}
  {id:  88, name: 'EQ B5 Frequency'         section=''}
  {id:  89, name: 'EQ B6 Frequency'         section=''}
  {id:  90, name: 'EQ B7 Frequency'         section=''}
  {id:  91, name: 'EQ B8 Frequency'         section=''}
  {id:  92, name: 'EQ HS Frequency'         section=''}
  {id:  93, name: 'EQ LP Frequency'         section=''}
  {id:  94, name: 'EQ LS Gain'              section=''}
  {id:  95, name: 'EQ B1 Gain'              section=''}
  {id:  96, name: 'EQ B2 Gain'              section=''}
  {id:  97, name: 'EQ B3 Gain'              section=''}
  {id:  98, name: 'EQ B4 Gain'              section=''}
  {id:  99, name: 'EQ B5 Gain'              section=''}
  {id: 100, name: 'EQ B6 Gain'              section=''}
  {id: 101, name: 'EQ B7 Gain'              section=''}
  {id: 102, name: 'EQ B8 Gain'              section=''}
  {id: 103, name: 'EQ HS Gain'              section=''}
  {id: 104, name: 'EQ HP Res Q'             section=''}
  {id: 105, name: 'EQ LS Q'                 section=''}
  {id: 106, name: 'EQ B1 Q'                 section=''}
  {id: 107, name: 'EQ B2 Q'                 section=''}
  {id: 108, name: 'EQ B3 Q'                 section=''}
  {id: 109, name: 'EQ B4 Q'                 section=''}
  {id: 110, name: 'EQ B5 Q'                 section=''}
  {id: 111, name: 'EQ B6 Q'                 section=''}
  {id: 112, name: 'EQ B7 Q'                 section=''}
  {id: 113, name: 'EQ B8 Q'                 section=''}
  {id: 114, name: 'EQ HS Q'                 section=''}
  {id: 115, name: 'EQ LP Res Q'             section=''}
  {id: 116, name: 'EQ LS Threshold'         section=''}
  {id: 117, name: 'EQ B1 Threshold'         section=''}
  {id: 118, name: 'EQ B2 Threshold'         section=''}
  {id: 119, name: 'EQ B3 Threshold'         section=''}
  {id: 120, name: 'EQ B4 Threshold'         section=''}
  {id: 121, name: 'EQ B5 Threshold'         section=''}
  {id: 122, name: 'EQ B6 Threshold'         section=''}
  {id: 123, name: 'EQ B7 Threshold'         section=''}
  {id: 124, name: 'EQ B8 Threshold'         section=''}
  {id: 125, name: 'EQ HS Threshold'         section=''}
  {id: 126, name: 'EQ HP Shape'             section=''}
  {id: 127, name: 'EQ LS Shape'             section=''}
  {id: 128, name: 'EQ B1 Shape'             section=''}
  {id: 129, name: 'EQ B2 Shape'             section=''}
  {id: 130, name: 'EQ B3 Shape'             section=''}
  {id: 131, name: 'EQ B4 Shape'             section=''}
  {id: 132, name: 'EQ B5 Shape'             section=''}
  {id: 133, name: 'EQ B6 Shape'             section=''}
  {id: 134, name: 'EQ B7 Shape'             section=''}
  {id: 135, name: 'EQ B8 Shape'             section=''}
  {id: 136, name: 'EQ HS Shape'             section=''}
  {id: 137, name: 'EQ LP Shape'             section=''}
  {id: 138, name: 'EQ HP Enable'            section=''}
  {id: 139, name: 'EQ LS Enable'            section=''}
  {id: 140, name: 'EQ B1 Enable'            section=''}
  {id: 141, name: 'EQ B2 Enable'            section=''}
  {id: 142, name: 'EQ B3 Enable'            section=''}
  {id: 143, name: 'EQ B4 Enable'            section=''}
  {id: 144, name: 'EQ B5 Enable'            section=''}
  {id: 145, name: 'EQ B6 Enable'            section=''}
  {id: 146, name: 'EQ B7 Enable'            section=''}
  {id: 147, name: 'EQ B8 Enable'            section=''}
  {id: 148, name: 'EQ HS Enable'            section=''}
  {id: 149, name: 'EQ LP Enable'            section=''}
  {id: 150, name: 'EQ LS Dyn Mode'          section=''}
  {id: 151, name: 'EQ B1 Dyn Mode'          section=''}
  {id: 152, name: 'EQ B2 Dyn Mode'          section=''}
  {id: 153, name: 'EQ B3 Dyn Mode'          section=''}
  {id: 154, name: 'EQ B4 Dyn Mode'          section=''}
  {id: 155, name: 'EQ B5 Dyn Mode'          section=''}
  {id: 156, name: 'EQ B6 Dyn Mode'          section=''}
  {id: 157, name: 'EQ B7 Dyn Mode'          section=''}
  {id: 158, name: 'EQ B8 Dyn Mode'          section=''}
  {id: 159, name: 'EQ HS Dyn Mode'          section=''}
  {id: 160, name: 'EQ LS is Static'         section=''}
  {id: 161, name: 'EQ B1 is Static'         section=''}
  {id: 162, name: 'EQ B2 is Static'         section=''}
  {id: 163, name: 'EQ B3 is Static'         section=''}
  {id: 164, name: 'EQ B4 is Static'         section=''}
  {id: 165, name: 'EQ B5 is Static'         section=''}
  {id: 166, name: 'EQ B6 is Static'         section=''}
  {id: 167, name: 'EQ B7 is Static'         section=''}
  {id: 168, name: 'EQ B8 is Static'         section=''}
  {id: 169, name: 'EQ HS is Static'         section=''}
  {id: 170, name: 'EQ Process LFE'          section=''}
  {id: 171, name: 'EQ Global Mix'           section=''}
  {id: 172, name: 'EXC B1 Bypass'           section=''}
  {id: 173, name: 'EXC B1 X'                section=''}
  {id: 174, name: 'EXC B1 Y'                section=''}
  {id: 175, name: 'EXC B1 Drive'            section=''}
  {id: 176, name: 'EXC B1 Blend'            section=''}
  {id: 177, name: 'EXC B2 Bypass'           section=''}
  {id: 178, name: 'EXC B2 X'                section=''}
  {id: 179, name: 'EXC B2 Y'                section=''}
  {id: 180, name: 'EXC B2 Drive'            section=''}
  {id: 181, name: 'EXC B2 Blend'            section=''}
  {id: 182, name: 'EXC B3 Bypass'           section=''}
  {id: 183, name: 'EXC B3 X'                section=''}
  {id: 184, name: 'EXC B3 Y'                section=''}
  {id: 185, name: 'EXC B3 Drive'            section=''}
  {id: 186, name: 'EXC B3 Blend'            section=''}
  {id: 187, name: 'EXC Post Filter Freq'    section=''}
  {id: 188, name: 'EXC Post Filter Gain'    section=''}
  {id: 189, name: 'EXC Global Filter Mode'  section=''}
  {id: 190, name: 'EXC Global Mix'          section=''}
  {id: 191, name: 'EXC Process LFE'         section=''}
  {id: 192, name: 'LIM Bypass'              section=''}
  {id: 193, name: 'LIM Algorithm'           section=''}
  {id: 194, name: 'LIM Ceiling'             section=''}
  {id: 195, name: 'LIM Character'           section=''}
  {id: 196, name: 'LIM Process LFE'         section=''}
  {id: 197, name: 'TS B1 Attack'            section=''}
  {id: 198, name: 'TS B1 Bypass'            section=''}
  {id: 199, name: 'TS B1 Contour'           section=''}
  {id: 200, name: 'TS B1 Sustain'           section=''}
  {id: 201, name: 'TS B2 Attack'            section=''}
  {id: 202, name: 'TS B2 Bypass'            section=''}
  {id: 203, name: 'TS B2 Contour'           section=''}
  {id: 204, name: 'TS B2 Sustain'           section=''}
  {id: 205, name: 'TS B3 Attack'            section=''}
  {id: 206, name: 'TS B3 Bypass'            section=''}
  {id: 207, name: 'TS B3 Contour'           section=''}
  {id: 208, name: 'TS B3 Sustain'           section=''}
  {id: 209, name: 'TS Global Mode'          section=''}
  {id: 210, name: 'TS Global Mix'           section=''}
  {id: 211, name: 'TS Process LFE'          section=''}
]