module.exports = [
  {id:  0, name: 'Global Bypass'      section=''}
  {id:  1, name: 'Global Dirty Flag'  section=''}
  {id:  2, name: 'Global Input Gain'  section=''}
  {id:  3, name: 'Global Output Gain' section=''}
  {id:  4, name: 'EQ HP Frequency'    section=''}
  {id:  5, name: 'EQ LS Frequency'    section=''}
  {id:  6, name: 'EQ B1 Frequency'    section=''}
  {id:  7, name: 'EQ B2 Frequency'    section=''}
  {id:  8, name: 'EQ B3 Frequency'    section=''}
  {id:  9, name: 'EQ B4 Frequency'    section=''}
  {id: 10, name: 'EQ B5 Frequency'    section=''}
  {id: 11, name: 'EQ B6 Frequency'    section=''}
  {id: 12, name: 'EQ B7 Frequency'    section=''}
  {id: 13, name: 'EQ B8 Frequency'    section=''}
  {id: 14, name: 'EQ HS Frequency'    section=''}
  {id: 15, name: 'EQ LP Frequency'    section=''}
  {id: 16, name: 'EQ LS Gain'         section=''}
  {id: 17, name: 'EQ B1 Gain'         section=''}
  {id: 18, name: 'EQ B2 Gain'         section=''}
  {id: 19, name: 'EQ B3 Gain'         section=''}
  {id: 20, name: 'EQ B4 Gain'         section=''}
  {id: 21, name: 'EQ B5 Gain'         section=''}
  {id: 22, name: 'EQ B6 Gain'         section=''}
  {id: 23, name: 'EQ B7 Gain'         section=''}
  {id: 24, name: 'EQ B8 Gain'         section=''}
  {id: 25, name: 'EQ HS Gain'         section=''}
  {id: 26, name: 'EQ HP Res Q'        section=''}
  {id: 27, name: 'EQ LS Q'            section=''}
  {id: 28, name: 'EQ B1 Q'            section=''}
  {id: 29, name: 'EQ B2 Q'            section=''}
  {id: 30, name: 'EQ B3 Q'            section=''}
  {id: 31, name: 'EQ B4 Q'            section=''}
  {id: 32, name: 'EQ B5 Q'            section=''}
  {id: 33, name: 'EQ B6 Q'            section=''}
  {id: 34, name: 'EQ B7 Q'            section=''}
  {id: 35, name: 'EQ B8 Q'            section=''}
  {id: 36, name: 'EQ HS Q'            section=''}
  {id: 37, name: 'EQ LP Res Q'        section=''}
  {id: 38, name: 'EQ LS Threshold'    section=''}
  {id: 39, name: 'EQ B1 Threshold'    section=''}
  {id: 40, name: 'EQ B2 Threshold'    section=''}
  {id: 41, name: 'EQ B3 Threshold'    section=''}
  {id: 42, name: 'EQ B4 Threshold'    section=''}
  {id: 43, name: 'EQ B5 Threshold'    section=''}
  {id: 44, name: 'EQ B6 Threshold'    section=''}
  {id: 45, name: 'EQ B7 Threshold'    section=''}
  {id: 46, name: 'EQ B8 Threshold'    section=''}
  {id: 47, name: 'EQ HS Threshold'    section=''}
  {id: 48, name: 'EQ HP Shape'        section=''}
  {id: 49, name: 'EQ LS Shape'        section=''}
  {id: 50, name: 'EQ B1 Shape'        section=''}
  {id: 51, name: 'EQ B2 Shape'        section=''}
  {id: 52, name: 'EQ B3 Shape'        section=''}
  {id: 53, name: 'EQ B4 Shape'        section=''}
  {id: 54, name: 'EQ B5 Shape'        section=''}
  {id: 55, name: 'EQ B6 Shape'        section=''}
  {id: 56, name: 'EQ B7 Shape'        section=''}
  {id: 57, name: 'EQ B8 Shape'        section=''}
  {id: 58, name: 'EQ HS Shape'        section=''}
  {id: 59, name: 'EQ LP Shape'        section=''}
  {id: 60, name: 'EQ HP Enable'       section=''}
  {id: 61, name: 'EQ LS Enable'       section=''}
  {id: 62, name: 'EQ B1 Enable'       section=''}
  {id: 63, name: 'EQ B2 Enable'       section=''}
  {id: 64, name: 'EQ B3 Enable'       section=''}
  {id: 65, name: 'EQ B4 Enable'       section=''}
  {id: 66, name: 'EQ B5 Enable'       section=''}
  {id: 67, name: 'EQ B6 Enable'       section=''}
  {id: 68, name: 'EQ B7 Enable'       section=''}
  {id: 69, name: 'EQ B8 Enable'       section=''}
  {id: 70, name: 'EQ HS Enable'       section=''}
  {id: 71, name: 'EQ LP Enable'       section=''}
  {id: 72, name: 'EQ LS Dyn Mode'     section=''}
  {id: 73, name: 'EQ B1 Dyn Mode'     section=''}
  {id: 74, name: 'EQ B2 Dyn Mode'     section=''}
  {id: 75, name: 'EQ B3 Dyn Mode'     section=''}
  {id: 76, name: 'EQ B4 Dyn Mode'     section=''}
  {id: 77, name: 'EQ B5 Dyn Mode'     section=''}
  {id: 78, name: 'EQ B6 Dyn Mode'     section=''}
  {id: 79, name: 'EQ B7 Dyn Mode'     section=''}
  {id: 80, name: 'EQ B8 Dyn Mode'     section=''}
  {id: 81, name: 'EQ HS Dyn Mode'     section=''}
  {id: 82, name: 'EQ LS is Static'    section=''}
  {id: 83, name: 'EQ B1 is Static'    section=''}
  {id: 84, name: 'EQ B2 is Static'    section=''}
  {id: 85, name: 'EQ B3 is Static'    section=''}
  {id: 86, name: 'EQ B4 is Static'    section=''}
  {id: 87, name: 'EQ B5 is Static'    section=''}
  {id: 88, name: 'EQ B6 is Static'    section=''}
  {id: 89, name: 'EQ B7 is Static'    section=''}
  {id: 90, name: 'EQ B8 is Static'    section=''}
  {id: 91, name: 'EQ HS is Static'    section=''}
  {id: 92, name: 'EQ Process LFE'     section=''}
  {id: 93, name: 'EQ Global Mix'      section=''}
]