#!/bin/sh -e
#
# convert .bwpreset to NKS PCHK chunk
#
#  PCHK chunk
#      32bit flags or int value, I think It means chunk version.
#    + data  pluginsstates
#
#  .bwpreset has pluginstae as zip format.
#   zipped part contains 160byte header + plauginstates
#

# unzip & remove first 156 byte
unzip -p "$1" | tail -c +157 > "$2"

# replace first 4 byte
printf '\x1\x0\x0\x0' | dd conv=notrunc of="$2" bs=4 seek=0
